/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	controlv1 "github.com/myhangshi/everest/pkg/apis/control/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeScalings implements ScalingInterface
type FakeScalings struct {
	Fake *FakeControlV1
	ns   string
}

var scalingsResource = schema.GroupVersionResource{Group: "control.example.com", Version: "v1", Resource: "scalings"}

var scalingsKind = schema.GroupVersionKind{Group: "control.example.com", Version: "v1", Kind: "Scaling"}

// Get takes name of the scaling, and returns the corresponding scaling object, and an error if there is any.
func (c *FakeScalings) Get(name string, options v1.GetOptions) (result *controlv1.Scaling, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(scalingsResource, c.ns, name), &controlv1.Scaling{})

	if obj == nil {
		return nil, err
	}
	return obj.(*controlv1.Scaling), err
}

// List takes label and field selectors, and returns the list of Scalings that match those selectors.
func (c *FakeScalings) List(opts v1.ListOptions) (result *controlv1.ScalingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(scalingsResource, scalingsKind, c.ns, opts), &controlv1.ScalingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &controlv1.ScalingList{ListMeta: obj.(*controlv1.ScalingList).ListMeta}
	for _, item := range obj.(*controlv1.ScalingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested scalings.
func (c *FakeScalings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(scalingsResource, c.ns, opts))

}

// Create takes the representation of a scaling and creates it.  Returns the server's representation of the scaling, and an error, if there is any.
func (c *FakeScalings) Create(scaling *controlv1.Scaling) (result *controlv1.Scaling, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(scalingsResource, c.ns, scaling), &controlv1.Scaling{})

	if obj == nil {
		return nil, err
	}
	return obj.(*controlv1.Scaling), err
}

// Update takes the representation of a scaling and updates it. Returns the server's representation of the scaling, and an error, if there is any.
func (c *FakeScalings) Update(scaling *controlv1.Scaling) (result *controlv1.Scaling, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(scalingsResource, c.ns, scaling), &controlv1.Scaling{})

	if obj == nil {
		return nil, err
	}
	return obj.(*controlv1.Scaling), err
}

// Delete takes name of the scaling and deletes it. Returns an error if one occurs.
func (c *FakeScalings) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(scalingsResource, c.ns, name), &controlv1.Scaling{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeScalings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(scalingsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &controlv1.ScalingList{})
	return err
}

// Patch applies the patch and returns the patched scaling.
func (c *FakeScalings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *controlv1.Scaling, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(scalingsResource, c.ns, name, pt, data, subresources...), &controlv1.Scaling{})

	if obj == nil {
		return nil, err
	}
	return obj.(*controlv1.Scaling), err
}
