/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/myhangshi/everest/pkg/apis/control/v1"
	scheme "github.com/myhangshi/everest/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ScalingsGetter has a method to return a ScalingInterface.
// A group's client should implement this interface.
type ScalingsGetter interface {
	Scalings(namespace string) ScalingInterface
}

// ScalingInterface has methods to work with Scaling resources.
type ScalingInterface interface {
	Create(*v1.Scaling) (*v1.Scaling, error)
	Update(*v1.Scaling) (*v1.Scaling, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Scaling, error)
	List(opts metav1.ListOptions) (*v1.ScalingList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Scaling, err error)
	ScalingExpansion
}

// scalings implements ScalingInterface
type scalings struct {
	client rest.Interface
	ns     string
}

// newScalings returns a Scalings
func newScalings(c *ControlV1Client, namespace string) *scalings {
	return &scalings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the scaling, and returns the corresponding scaling object, and an error if there is any.
func (c *scalings) Get(name string, options metav1.GetOptions) (result *v1.Scaling, err error) {
	result = &v1.Scaling{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("scalings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Scalings that match those selectors.
func (c *scalings) List(opts metav1.ListOptions) (result *v1.ScalingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ScalingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("scalings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested scalings.
func (c *scalings) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("scalings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a scaling and creates it.  Returns the server's representation of the scaling, and an error, if there is any.
func (c *scalings) Create(scaling *v1.Scaling) (result *v1.Scaling, err error) {
	result = &v1.Scaling{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("scalings").
		Body(scaling).
		Do().
		Into(result)
	return
}

// Update takes the representation of a scaling and updates it. Returns the server's representation of the scaling, and an error, if there is any.
func (c *scalings) Update(scaling *v1.Scaling) (result *v1.Scaling, err error) {
	result = &v1.Scaling{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("scalings").
		Name(scaling.Name).
		Body(scaling).
		Do().
		Into(result)
	return
}

// Delete takes name of the scaling and deletes it. Returns an error if one occurs.
func (c *scalings) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("scalings").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *scalings) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("scalings").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched scaling.
func (c *scalings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Scaling, err error) {
	result = &v1.Scaling{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("scalings").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
