/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	controlv1 "github.com/myhangshi/everest/pkg/apis/control/v1"
	versioned "github.com/myhangshi/everest/pkg/client/clientset/versioned"
	internalinterfaces "github.com/myhangshi/everest/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/myhangshi/everest/pkg/client/listers/control/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ScalingInformer provides access to a shared informer and lister for
// Scalings.
type ScalingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ScalingLister
}

type scalingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewScalingInformer constructs a new informer for Scaling type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewScalingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredScalingInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredScalingInformer constructs a new informer for Scaling type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredScalingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ControlV1().Scalings(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ControlV1().Scalings(namespace).Watch(options)
			},
		},
		&controlv1.Scaling{},
		resyncPeriod,
		indexers,
	)
}

func (f *scalingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredScalingInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *scalingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&controlv1.Scaling{}, f.defaultInformer)
}

func (f *scalingInformer) Lister() v1.ScalingLister {
	return v1.NewScalingLister(f.Informer().GetIndexer())
}
